[package]
name = "drink_water"
version = "0.1.0"
authors = ["Renato Assis <renatoweverton@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify-rust = "^3"
job_scheduler = "*"